# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
    - name: Set up Python 3.8
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update -f environment.yml -n base
        
    - name: Run pytest
      run: |
        make testcov COVERAGE=$CONDA/bin/coverage

    - name: Upload coverage
      run: |
        $CONDA/bin/codecov
